version: '3.6'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - $HARBOUR/apps/flame:/app/data
    expose:
      - 5005
    environment:
      - PASSWORD=$PASSWORD
    restart: unless-stopped
networks:
  default:
    external: true
    name: $DOCKER_NETWORK
