version: "3.7"
networks:
  default:
    external: true
    name: $DOCKER_NETWORK

services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - $HARBOUR/apps/uptime_kuma:/app/data
    expose:
      - 3001
    restart: always
