version: '3.4'
networks:
  default:
    external: true
    name: $DOCKER_NETWORK

secrets:
  minirss_postgre_magic:
    file: $HARBOUR/magics/minirss_postgre_magic
  minirss_postgre_url:
    file: $HARBOUR/magics/minirss_postgre_url
  minirss_admin_magic:
    file: $HARBOUR/magics/minirss_admin_magic

services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    secrets:
      - minirss_admin_magic
      - minirss_postgre_url
    expose:
      - 8080
    depends_on:
      - minirss_db
    volumes:
      - $HARBOUR/apps/mini_rss/config:/etc
    environment:
      - DATABASE_URL_FILE=/run/secrets/minirss_postgre_url
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=$MINIFLUX_ADMIN
      - ADMIN_PASSWORD_FILE=/run/secrets/minirss_admin_magic
    restart: always
    networks:
      default:
        ipv4_address: $IP_MINIFLUX

  minirss_db:
    image: postgres:latest
    container_name: minirss_db
    restart: always
    secrets:
      - minirss_postgre_magic
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD_FILE=/run/secrets/minirss_postgre_magic
    volumes:
      - $HARBOUR/apps/mini_rss/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
