version: "3.4"
services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.15.0
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    volumes:
      - $HARBOUR/door/netmaker/dnsconfig:/root/config/dnsconfig
      - $HARBOUR/door/netmaker/sqldata:/root/data
      - $HARBOUR/door/netmaker/shared_certs:/etc/netmaker
    environment:
      SERVER_NAME: $BROKER_DOMAIN
      SERVER_HOST: $IP_SERVER
      SERVER_API_CONN_STRING: $API_DOMAIN_PORT
      COREDNS_ADDR: $IP_SERVER
      DNS_MODE: "on"
      SERVER_HTTP_HOST: $API_DOMAIN
      API_PORT: $API_PORT
      CLIENT_MODE: "on"
      MASTER_KEY: $NETMAKER_MASTER_KEY
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      NODE_ID: $NETMAKER_HUB_ID
      MQ_HOST: $MQ_HOST
      MQ_PORT: $MQ_PORT
      MQ_SERVER_PORT: $MQ_SERVER_PORT
      HOST_NETWORK: "off"
      VERBOSITY: "1"
      MANAGE_IPTABLES: "on"
      PORT_FORWARD_SERVICES: "dns"
      AUTH_PROVIDER: $OIDC_SSO
      CLIENT_ID: $OIDC_CLIENT_ID
      CLIENT_SECRET: $OIDC_CLIENT_SECRET
      FRONTEND_URL: $DASHBOARD_DOMAIN

    ports:
      - "51821-51830:51821-51830/udp"
    expose:
      - 8081

  netmaker-ui:
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:v0.15.0
    depends_on:
      - netmaker
    links:
      - "netmaker:api"
    restart: always
    environment:
      BACKEND_URL: $API_DOMAIN
    expose:
      - 80

  coredns:
    container_name: coredns
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    depends_on:
      - netmaker
    restart: always
    volumes:
      - $HARBOUR/door/netmaker/dnsconfig:/root/dnsconfig

  mq:
    container_name: mq
    image: eclipse-mosquitto:2.0.11-openssl
    depends_on:
      - netmaker
    restart: unless-stopped
    volumes:
      - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $HARBOUR/door/netmaker/mosquitto_data:/mosquitto/data
      - $HARBOUR/door/netmaker/mosquitto_logs:/mosquitto/log
      - $HARBOUR/door/netmaker/shared_certs:/mosquitto/certs
    ports:
      - 8883:8883
    networks:
      default:
        ipv4_address: $IP_MQ

networks:
  default:
    external: true
    name: $DOCKER_NETWORK
